%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(animals_thrift).
-behaviour(thrift_service).


-include("animals_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% create(This, Request)
function_info('create', params_type) ->
  {struct, [{1, {struct, {'animals_types', 'AnimalsCreateRequest'}}}]}
;
function_info('create', reply_type) ->
  {struct, {'animals_types', 'AnimalsCreateResponse'}};
function_info('create', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

