%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(animals_types).

-include("animals_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Animal') ->
  {struct, [{1, i32},
          {2, i32}]}
;

struct_info('AnimalsCreateRequest') ->
  {struct, [{1, {struct, {'animals_types', 'Animal'}}}]}
;

struct_info('AnimalsCreateResponse') ->
  {struct, [{1, {struct, {'animals_types', 'Animal'}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Animal') ->
  {struct, [{1, undefined, i32, 'id', undefined},
          {2, undefined, i32, 'type', undefined}]}
;

struct_info_ext('AnimalsCreateRequest') ->
  {struct, [{1, required, {struct, {'animals_types', 'Animal'}}, 'animal', #'Animal'{}}]}
;

struct_info_ext('AnimalsCreateResponse') ->
  {struct, [{1, optional, {struct, {'animals_types', 'Animal'}}, 'animal', #'Animal'{}}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

